### ISSUE TITLE
ERROR message is not causing uploader to fail

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-uploader#278] opened 2020-07-28 12:13 UTC
Following ERROR message is not causing uploader to fail when it should.

```
2020-07-28 21:48:17+1200: linz_bde_uploader: 2020/07/28 21:48:17 ERROR> BdeUpload.pm:681 - Cannot load incremental updates to crs_ttl_inst_protect as there is no previous upload

```

**Comment by strk** [comment] 2020-08-11 11:58
There are many cases in lib/LINZ/BdeUpload.pm of ERROR lines not followed by some error return code, enough to look like desired behavior. In particular, I see 2 lines, one after the other, both calling ERROR (from log4perl) which suggests it isn't expected for ERROR to throw an exception (or die). How can we tell which errors we want to be fatal and which error we do not ? Should every ERROR be fatal instead ? \cc @palmerj

**Comment by strk** [comment] 2020-09-08 14:37
I'm concluding that this was done by design (to continue import when incremental tables exist without a previous full table) so I'm closing this

**Closed by strk** 2020-09-08 14:37 UTC
Labels: bug
